DECLARE var_gl VARCHAR2(20) := 'VARIABLE GLOBALE';

BEGIN DECLARE var_loc VARCHAR2(20) := 'VARIABLE LOCALE';

BEGIN DBMS_OUTPUT.PUT_LINE(var_loc);

DBMS_OUTPUT.PUT_LINE(var_gl);

--END;
DBMS_OUTPUT.PUT_LINE(var_loc);

DBMS_OUTPUT.PUT_LINE(var_gl);

END;

END;

/